### ISSUE TITLE
Spike: set up appscript

### ISSUE THREAD

**Issue by cwolfe007** [cwolfe007/chatgpt_job#3]
Look into app script and determine what work will be needed

**Comment by bradenericson** [comment]
Learnings: 
- AppScript would allow for an easy javascript-ish way to interact with the Google Document to do find and replace queries.
- You can bind AppScript scripts to a document or run them as an add-on or HTTP service
- To leverage AppScript within this project, we'd need to set up a separate environment for the AppScript code, or leverage something like clasp cli to have a separate space in the project for AppScript files. 

OVERALL RECCOMENDATION 
- Considering we can do everything we need with the Google Drive API, and already have the Drive SDK set up in our script, we should continue to just use the Drive SDK to run any Google Doc queries or manipulations. The inclusion of the `documents` scope in my last PR will allow us to run commands on a generated resume (e.g. Find and Replace) directly from the SDK without needing any additional permissions or setup.
